import React from "react";
import Head from "next/head";
import Grid from "@material-ui/core/Grid";
import { makeStyles } from "@material-ui/core/styles";
import { Formik } from "formik";
import * as Yup from "yup";
import Input from "../../../components/default/form/input";
import Textarea from "../../../components/default/form/textarea";
import Button from "../../../components/default/form/button";
import Typography from "@material-ui/core/Typography";
import Box from "@material-ui/core/Box";
import Card from "@material-ui/core/Card";
import InputAdornment from "@material-ui/core/InputAdornment";
import { Person, PermDeviceInformation, Label } from "@material-ui/icons";
import IconButton from "@material-ui/core/IconButton";

// regex
const usernameRegex = /^[A-Za-z '']+$/;

const useStyles = makeStyles((theme) => ({
  root: {
    flexGrow: 1,
  },
  paper: {
    padding: theme.spacing(2),
    textAlign: "center",
    color: theme.palette.text.secondary,
  },
  card: {
    padding: "36px",
    marginTop: "19px",
  },
}));

const Symptoms = () => {
  const classes = useStyles();

  const [values, setValues] = React.useState({
    showComfirmPassword: false,
    showPassword: false,
  });

  const handleClickShowPassword = () => {
    setValues({
      ...values,
      showPassword: !values.showPassword,
    });
  };
  const handleClickComfirmPassword = () => {
    setValues({
      ...values,

      showComfirmPassword: !values.showComfirmPassword,
    });
  };

  return (
    <div className={classes.root}>
      <Head>
        <title>Add Symptoms</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container spacing={3}>
        <Grid item xs={12} md={3} sm={12}></Grid>
        <Grid item xs={12} md={6} sm={12}>
          <Card className={classes.card}>
            <Box py={3}>
              <Typography variant="h4" color="primary" align="left">
                Add Symptoms
              </Typography>
            </Box>
            <Formik
              initialValues={{
                title: "",
                causes: "",
                solutions: "",
              }}
              validationSchema={Yup.object({
                title: Yup.string()
                  .min(3, "Title must be atleast 3 characters")
                  .max(120, "Title is too Long!")
                  .matches(
                    usernameRegex,
                    "Only alphabets are allowed for this field "
                  )
                  .required("Title is required"),
                causes: Yup.string()
                  .matches(usernameRegex, "Causes is invalid ")
                  .required("Causes is required"),
                solutions: Yup.string()
                  .matches(usernameRegex, "solutions is invalid ")
                  .required("Solutions is required"),
              })}
              onSubmit={(values, actions) => {
                console.log(values);
              }}
            >
              {(props) => (
                <form onSubmit={props.handleSubmit}>
                  <Input
                    type="text"
                    onChange={props.handleChange}
                    onBlur={props.handleBlur}
                    value={props.values.username}
                    label="Title"
                    name="title"
                    error={props.errors.title ? true : false}
                    errortext={props.errors.title}
                    InputProps={{
                      endAdornment: (
                        <InputAdornment position="start">
                          <IconButton edge="end">
                            {<Person color="primary" />}
                          </IconButton>
                        </InputAdornment>
                      ),
                    }}
                  />

                  {/* causes */}
                  <Textarea
                    label="Causes"
                    InputProps={{
                      endAdornment: (
                        <InputAdornment position="start">
                          <IconButton edge="end">
                            {<PermDeviceInformation color="primary" />}
                          </IconButton>
                        </InputAdornment>
                      ),
                    }}
                    name="causes"
                    onChange={props.handleChange}
                    onBlur={props.handleBlur}
                    value={props.values.causes}
                    error={props.errors.causes ? true : false}
                    errortext={props.errors.causes}
                  />

                  {/*solutions  */}
                  <Textarea
                    label="Solutions"
                    InputProps={{
                      endAdornment: (
                        <InputAdornment position="start">
                          <IconButton edge="end">
                            {<Label color="primary" />}
                          </IconButton>
                        </InputAdornment>
                      ),
                    }}
                    name="solutions"
                    onChange={props.handleChange}
                    onBlur={props.handleBlur}
                    value={props.values.solutions}
                    error={props.errors.solutions ? true : false}
                    errortext={props.errors.solutions}
                  />

                  <Button label="Submit" type="submit" />
                </form>
              )}
            </Formik>
          </Card>
        </Grid>
        <Grid item xs={12} md={3} sm={12}></Grid>
      </Grid>
    </div>
  );
};

Symptoms.layout = "DashboardLayout";
export default Symptoms;
