import React, { useEffect } from "react";
import { Notify } from "notiflix";
import Head from "next/head";
import Box from "@material-ui/core/Box";
import Grid from "@material-ui/core/Grid";
import Typography from "@material-ui/core/Typography";
import Paper from "@material-ui/core/Paper";
// import styles from "../styles/Home.module.css";

const Home = () => {
  useEffect(() => {
    Notify.success("Welcome to Car Expert");
  }, []);

  return (
    <Box>
      <Head>
        <title>Car Expert App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Grid container>
          <Grid item md={12} sm={12} xs={12}>
            <Box my={5}>
              <Typography color="primary" variant="h4" align="center" paragraph>
                TOYOTA KNOWLEDGEBASE
              </Typography>
            </Box>
            <Box my={5}>
              <Typography variant="body1" align="center">
                Diagnose your car without pains or stress at your comfort
              </Typography>
            </Box>
            <Paper elevation={12} py={5} px={5}>
              <h1>table will be here</h1>
            </Paper>
          </Grid>
        </Grid>
      </main>
    </Box>
  );
};
Home.layout = "defaultLayout";
export default Home;
