import React from "react";
import Head from "next/head";
import Grid from "@material-ui/core/Grid";
const baseUrl = "http://localhost:5000/api/v1/cars";
import Paper from "@material-ui/core/Paper";
import Typography from "@material-ui/core/Typography";
import Box from "@material-ui/core/Box";

export const getStaticPaths = async () => {
  const res = await fetch(`${baseUrl}/car`);
  const data = await res.json();
  const carsList = data.cars.data;
  const paths = carsList.map((sid) => {
    return {
      params: { id: sid.id.toString() },
    };
  });
  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps = async (context) => {
  const id = context.params.id;
  const res = await fetch(`${baseUrl}/car/${id}`);
  const data = await res.json();
  const carsList = data.car;
  return {
    props: { car: carsList },
  };
};

const Fault = ({ car }) => {
  return (
    <>
      <Head>
        <title>Fault</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container>
        <Grid item sm={12} md={2} xs={12}></Grid>
        <Grid item sm={12} md={8} xs={12}>
          <Box mt={4}>
            <Paper
              elevation={2}
              py={6}
              style={{
                padding: "30px 34px",
              }}
            >
              <Typography
                color="primary"
                variant="h3"
                style={{
                  textAlign: "center",
                }}
              >
                Car Faults Details
              </Typography>
              <br />
              <Typography color="primary" variant="h6">
                Car Fault:
              </Typography>
              <p>{car.symptoms}</p>
              {/*  */}
              <br />
              <Typography color="primary" variant="h6">
                Causes:
              </Typography>
              <p>{car.causes}</p>
              <Typography color="primary" variant="h6">
                Solutions:
              </Typography>
              <p>{car.solution}</p>
              <Typography color="primary" variant="h6">
                Car Type:
              </Typography>
              <p>{car.carType}</p>
            </Paper>
          </Box>
        </Grid>
        <Grid item sm={12} md={2} xs={12}></Grid>
      </Grid>
    </>
  );
};

Fault.layout = "defaultLayout";
export default Fault;
